[package]
name = "shutup-bot"
version = "2.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.40"
chrono-tz = "0.10.3"
clap = { version = "4.5.37", features = ["derive"] }
dptree = "0.3.0"
expanduser = "1.2.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
teloxide = { version = "0.15.0", features = ["macros", "tracing"] }
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
tracing-journald = "0.3.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
